---
#---------------- Chaincode Deployment ---------------------
apiVersion: apps/v1 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: chaincode-basic-match
  labels:
    app: chaincode-basic-match
spec:
  selector:
    matchLabels:
      app: chaincode-basic-match
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: chaincode-basic-match
    spec:
      containers:
        - image: quanglathe/basic-chaincode-hlf:1.0
          imagePullPolicy: Always
          name: chaincode-basic-match
          env:
            - name: CHAINCODE_ID
              value: 'basic:cd70a22f21dde853ea2c7fa4465cf25393fbf5ec295f09f80ebdcc94e7b466de'
            - name: CHAINCODE_SERVER_ADDRESS
              value: '0.0.0.0:7052'
          ports:
            - containerPort: 7052
