apiVersion: v1
kind: Service
metadata:
  name: ca-match
  labels:
    app: ca-match
spec:
  type: ClusterIP
  selector:
    app: ca-match
  ports:
    - protocol: TCP
      targetPort: 7054
      port: 7054
