kind: Service
apiVersion: v1
metadata:
  name: peer0-match
  labels:
    app: peer0-match
spec:
  selector:
    name: peer0-match
  type: ClusterIP
  ports:
    - name: grpc
      port: 7051
      protocol: TCP
    - name: event
      port: 7061
      protocol: TCP
    - name: couchdb
      port: 5984
      protocol: TCP

---
#---------------- Peer0 Match Metrics Service ---------------
apiVersion: v1
kind: Service
metadata:
  labels:
    app: peer0-match
    metrics-service: 'true'
  name: peer0-match-metrics
spec:
  type: ClusterIP
  ports:
    - name: 'peer-metrics'
      port: 9443
      targetPort: 9443
  selector:
    name: peer0-match
